#!/usr/bin/env python3
"""Render CATALOG.md from marketplace.json + changelogs + .upstream.json/.scorecard.json sidecars. Never exits nonzero for API failures."""
import json
import re
import sys
import urllib.request
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def github_stars(repo: str) -> str:
    import os
    req = urllib.request.Request(f"https://api.github.com/repos/{repo}",
                                 headers={"Accept": "application/vnd.github+json", "User-Agent": "claude-plugin-marketplace"})
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            n = json.load(r).get("stargazers_count", 0)
        return f"⭐ {n / 1000:.1f}k" if n >= 1000 else f"⭐ {n}"
    except Exception as e:  # catalog must never block publishing
        print(f"  warning: stars lookup failed for {repo}: {e}", file=sys.stderr)
        return "⭐ ?"


def tier_of(entry: dict) -> str:
    for t in entry.get("tags", []):
        m = re.match(r"^tier-([123])$", t)
        if m:
            return {"1": "T1 prompt-only", "2": "T2 read/config", "3": "T3 code-executing"}[m.group(1)]
    return "untiered"


def scorecard_of(name: str) -> str:
    sidecar = REPO / "plugins" / name / ".scorecard.json"
    if not sidecar.is_file():
        return "—"
    sc = json.loads(sidecar.read_text())
    mark = {True: "✔", False: "✗", None: "·"}
    cells = [f"scan {mark.get(sc.get('risk_lint'), '·')}",
             f"smoke {mark.get(sc.get('smoke_test'), '·')}"]
    if sc.get("llm_review") is not None:
        cells.append(f"LLM {mark[bool(sc['llm_review'])]}")
    if sc.get("upstream_fresh") is not None:
        cells.append("fresh" if sc["upstream_fresh"] else "drifted")
    return " ".join(cells) + (f" ({sc.get('date', '?')})" if sc.get("date") else "")


def main() -> int:
    mp = json.loads((REPO / ".claude-plugin" / "marketplace.json").read_text())
    market = mp.get("name", "internal")
    lines = [
        "# Plugin Catalog",
        "",
        f"_Generated by `scripts/build_catalog.py` on {date.today().isoformat()} — do not hand-edit._",
        "",
        f"Install any plugin with `/plugin install <name>@{market}`.",
        "",
        "| Plugin | Version | Risk tier | Scorecard | Category | Upstream | Description |",
        "|---|---|---|---|---|---|---|",
    ]
    for e in sorted(mp.get("plugins", []), key=lambda x: x["name"]):
        name = e["name"]
        upstream = "—"
        sidecar = REPO / "plugins" / name / ".upstream.json"
        if sidecar.is_file():
            up = json.loads(sidecar.read_text())
            repo = up.get("repo", "")
            upstream = f"[{repo}](https://github.com/{repo}) {github_stars(repo)} (v{up.get('upstreamVersion', '?')})"
        changelog = f"[{e['version']}](plugins/{name}/CHANGELOG.md)"
        lines.append(f"| **{e.get('displayName', name)}** (`{name}`) | {changelog} | {tier_of(e)} "
                     f"| {scorecard_of(name)} | {e.get('category', '—')} | {upstream} | {e.get('description', '')} |")
    lines += [
        "",
        "## Risk tiers",
        "- **T1 prompt-only** — markdown only, no code execution.",
        "- **T2 read/config** — read-only shell or allowlisted MCP servers.",
        "- **T3 code-executing** — hooks, local MCP processes, or bundled executables. Reviewed hardest.",
        "",
        "To submit a plugin, see the [README](README.md) or run `/new-plugin`.",
        "",
    ]
    (REPO / "CATALOG.md").write_text("\n".join(lines))
    print(f"catalog: wrote CATALOG.md ({len(mp.get('plugins', []))} plugins)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
