#!/usr/bin/env bash
# JumpCloud command (runs as root): deploy the managed Claude Code settings. Generated by scripts/apply_config.py — do not hand-edit.
set -euo pipefail
cd / # MDM agents run commands from a root-only CWD; sudo'd tools (git/brew/npm) fail getcwd there
TARGET="/Library/Application Support/ClaudeCode/managed-settings.json"
EXPECTED_SHA="f8e4168ca5459baac8d3a84399509c4b1829e0599fe1c43cac9574fc1d14cf5d"

if [ -f "$TARGET" ] && [ "$(shasum -a 256 "$TARGET" | awk '{print $1}')" = "$EXPECTED_SHA" ]; then
  echo "push-managed-settings: already current ($EXPECTED_SHA)"
  exit 0
fi
mkdir -p "$(dirname "$TARGET")"
TMP="$(mktemp)"
cat > "$TMP" <<'MANAGED_SETTINGS_EOF'
{
  "extraKnownMarketplaces": {
    "internal": {
      "source": {
        "source": "github",
        "repo": "francobee/claude-plugin-marketplace"
      }
    }
  },
  "strictKnownMarketplaces": [
    {
      "source": "github",
      "repo": "francobee/claude-plugin-marketplace"
    }
  ],
  "disableSideloadFlags": true,
  "enabledPlugins": {
    "company-essentials@internal": true
  }
}
MANAGED_SETTINGS_EOF
install -m 0644 -o root -g wheel "$TMP" "$TARGET"
rm -f "$TMP"
echo "push-managed-settings: wrote $TARGET ($EXPECTED_SHA) — Claude Code picks it up on next launch"
